World_Name: "world_mines"
Distance_Between_Mines: 100

# NORMAL, NETHER, THE_END (ender dragon spawns)
World_Type: NORMAL

Biome: PLAINS
Border_Radius: 20
Max_Mine_Player_Size: 3
Reset_All_Mines_Seconds: 60
Reset_Mine_Reminder_Every_Seconds: 30